### ISSUE TITLE
Argument missing at line 167

### ISSUE THREAD

**Issue by frogale** [davorf/BlackBeanControl#30]
Hello.. It looks like you have error at line 167..
RM3Device = broadlink.rm((RealIPAddress, RealPort), RealMACAddress)
TypeError: __init__() takes exactly 4 arguments (3 given)

After adding "RealTimeout" as 4th argument it is working just fine...

**Comment by ghost** [comment]
@frogale I have exactly the same error. Can you please help what file you exactly changed and post your code?

**Comment by jnherm** [comment]
I have edited line 167: 
RM3Device = broadlink.rm((RealIPAddress, RealPort), RealMACAddress, RealTimeout)

made it to work.

**Comment by JDrewes** [comment]
I had the same problem, frogale's solution made it work for me as well.

**Comment by lamerjack** [comment]
now the error is:
Traceback (most recent call last):
  File "./BlackBeanControl.py", line 168, in <module>
    RM3Device.auth()
  File "/usr/local/lib/python2.7/dist-packages/broadlink-0.13.0-py2.7.egg/broadlink/__init__.py", line 221, in auth
    response = self.send_packet(0x65, payload)
  File "/usr/local/lib/python2.7/dist-packages/broadlink-0.13.0-py2.7.egg/broadlink/__init__.py", line 271, in send_packet
    checksum = adler32(payload, 0xbeaf) & 0xffff
TypeError: adler32() argument 1 must be string or read-only buffer, not bytearray
