### ISSUE TITLE
line 3, in  import broadlink, configparser

### ISSUE THREAD

**Issue by simonkp** [davorf/BlackBeanControl#34]
I have set it up on my raspberry pi 3 and it was working without issues. Suddenly it stopped working and i am getting the following error when i run the command.

/usr/bin/python2 /usr/share/openhab2/exec/BlackBeanControl/BlackBeanControl.py -c FANON
Traceback (most recent call last):
  File "/usr/share/openhab2/exec/BlackBeanControl/BlackBeanControl.py", line 3, in <module>
    import broadlink, configparser
  File "/usr/local/lib/python2.7/dist-packages/broadlink-0.9-py2.7.egg/broadlink/__init__.py", line 5, in <module>
    from Crypto.Cipher import AES
  File "/usr/local/lib/python2.7/dist-packages/pycryptodome-3.4.11-py2.7-linux-armv7l.egg/Crypto/Cipher/__init__.py", line 7, in <module>
    from Crypto.Cipher._mode_ctr import _create_ctr_cipher
  File "/usr/local/lib/python2.7/dist-packages/pycryptodome-3.4.11-py2.7-linux-armv7l.egg/Crypto/Cipher/_mode_ctr.py", line 35, in <module>
    from Crypto.Util.number import long_to_bytes
ValueError: bad marshal data (unknown type code)

If I use python3 i get the following error

[21:23:53] openhabian@openHABianPi:/usr/share/openhab2/exec/BlackBeanControl$ sudo python3 BlackBeanControl.py  -c FANON  File "BlackBeanControl.py", line 197
    if (len(SentCommand) <> 8) or (not all(c in string.hexdigits for c in SentCommand)):
                          ^
SyntaxError: invalid syntax

**Comment by simonkp** [comment]
I just uninstalled pycryptodome and it started working again

sudo pip uninstall pycryptodome
